### PR TITLE
New Workflows

### PR DESCRIPTION
**Pull request by Mbucari**
I recently rejuggered my AAXClean build and publish workflows, and I thought you might like an update to AudibleApi.

Change Log:
- Unit Tests are run on every commit, and the action fails if the tests fail
- AudibleApi.Common is no longer its own nuget package and is instead packed inside AudibleApi.nupkg
- README.md is included inside AudibleApi.nupkg
- LICENSE is included inside AudibleApi.nupkg
- Added [Source Link](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)

The only difference for you is that when you update Dinah.Core, you need to update the version inside AudibeApi.nuspec.

### CODE REVIEW

**Comment by rmcrackan** [comment]
> AudibleApi.Common is no longer its own nuget package and is instead packed inside AudibleApi.nupkg

Yeah, this was probably overdue. I always thought there might eventually be a need for the lightweight common contracts separate from the heavy-duty audible api library. That never really happened though.

> when you update Dinah.Core, you need to update the version inside AudibeApi.nuspec

What happens if I don't remember? Because realistically I won't.

**Comment by Mbucari** [comment]
> Very interestingly, _nothing_ happens.

That's to say, everything still works as intended.

**Comment by rmcrackan** [comment]
That's just weird

**Comment by Mbucari** [comment]
> That's just weird

Very. I'm glad you asked the question and I'm glad I tested it out, so now I don't have to change my nusecs anymore 😄

**Pull request merged**
